"use client";

import React from "react";
import {
  Avatar,
  Badge,
  Card,
  CardBody,
  Typography,
} from "@material-tailwind/react";
import Image from "next/image";

import { Cabin } from "next/font/google";
const cabin = Cabin({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  Menu,
  MenuHandler,
  MenuList,
  MenuItem,
  Button,
} from "@material-tailwind/react";
import { Doughnut } from "react-chartjs-2";
import { Chart, ArcElement } from "chart.js";
Chart.register(ArcElement);

const chartData = {
  datasets: [
    {
      data: [2, 2, 2],
      backgroundColor: ["#336699", "#99CCFF", "#666666"],
      display: true,
      borderColor: "#D1D6DC",
    },
  ],
};

export default function GraphCard({ data }: any) {
  return (
    <div className="w-full bg-green-400">
      {/* <div className="flex justify-between">
      </div> */}
      <Doughnut
        data={chartData}
        options={{
          plugins: {
            legend: {
              display: false,
            },
            tooltip: {
              enabled: false,
            },
          },
          rotation: -90,
          circumference: 180,
          cutout: "90%",
          maintainAspectRatio: true,
          responsive: true,
        }}
      />
    </div>
  );
}
