"use client";

import React from "react";
import { Avatar, Card, CardBody, Typography } from "@material-tailwind/react";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  Menu,
  MenuHandler,
  MenuList,
  MenuItem,
  Button,
} from "@material-tailwind/react";

<Menu>
  <MenuHandler>
    <Button>Open Menu</Button>
  </MenuHandler>
  <MenuList>
    <MenuItem>Menu Item 1</MenuItem>
    <MenuItem>Menu Item 2</MenuItem>
    <MenuItem>Menu Item 3</MenuItem>
  </MenuList>
</Menu>;

export default function NavSearchbar() {
  return (
    <Card className="w-[40%] rounded-md px-4 py-2">
      <div className="flex my-4 mx-2">
        <div className="flex gap-x-4 ml-5 mt-4">
          <div className="relative inline-flex w-fit">
            <Menu>
              <div className="absolute bottom-auto left-auto right-0 top-0 z-10 inline-block -translate-y-[2px] translate-x-2/4 rotate-0 skew-x-0 skew-y-0 scale-x-100 scale-y-100 rounded-full bg-[#F65A27] px-[3.4px] py-[0.6px] border-2 border-white w-4 h-4">
                <p className="text-[8px] text-white">3</p>
              </div>
              <MenuHandler>
                <div className="flex items-center justify-center rounded-full bg-[#4D91FF] px-2 py-2 text-center text-white shadow-lg dark:text-gray-200 w-10 h-10">
                  <Image alt="" src="/message.svg" width={20} height={20} />
                </div>
              </MenuHandler>
              <MenuList>
                <MenuItem>Message 1</MenuItem>
                <MenuItem>Message 2</MenuItem>
                <MenuItem>Message 3</MenuItem>
              </MenuList>
            </Menu>
          </div>

          <div className="relative inline-flex w-fit">
            <Menu>
              <div className="absolute bottom-auto left-auto right-0 top-0 z-10 inline-block -translate-y-[2px] translate-x-2/4 rotate-0 skew-x-0 skew-y-0 scale-x-100 scale-y-100 rounded-full bg-[#F65A27] px-[3.4px] py-[0.6px] border-2 border-white w-4 h-4">
                <p className="text-[8px] text-white">3</p>
              </div>
              <MenuHandler>
                <div className="flex items-center justify-center rounded-full bg-[#4D91FF] px-2 py-2 text-center text-white shadow-lg dark:text-gray-200 w-10 h-10">
                  <Image alt="" src="/Alert.svg" width={20} height={20} />
                </div>
              </MenuHandler>
              <MenuList>
                <MenuItem>Notification 1</MenuItem>
                <MenuItem>Notification 2</MenuItem>
                <MenuItem>Notification 3</MenuItem>
              </MenuList>
            </Menu>
          </div>
        </div>
        <div className="ml-8 mt-2 flex">
          <Avatar
            src="/user.svg"
            className="bg-[#FFBC35] p-1"
            alt="avatar"
            size="lg"
          />
          <div className="ml-3 mt-[-8px]  text-black">
            <p className="font-bold text-[20px]">Demo User</p>
            <p className="text-[8px]">
              Account Id: f48cda68-448b-4c67-9828-f48cda68
            </p>
            <p className="text-[8px]">Namespace: Demo (c60c671bf1410535)</p>

            <p className="text-[8px]">Usage Intent: Basic Analysis</p>
          </div>
        </div>
      </div>
    </Card>
  );
}
