"use client";

import React from "react";
import { Avatar, Card, CardBody, Typography } from "@material-tailwind/react";
import Image from "next/image";

import { Cabin } from "next/font/google";
const cabin = Cabin({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  Menu,
  MenuHandler,
  MenuList,
  MenuItem,
  Button,
} from "@material-tailwind/react";

<Menu>
  <MenuHandler>
    <Button>Open Menu</Button>
  </MenuHandler>
  <MenuList>
    <MenuItem>Menu Item 1</MenuItem>
    <MenuItem>Menu Item 2</MenuItem>
    <MenuItem>Menu Item 3</MenuItem>
  </MenuList>
</Menu>;

export default function NavSearchbar() {
  return (
    <Card
      className={`w-[32vw] 4xl:h-[11vh] rounded-md px-4 py-2 ${cabin.className}`}
    >
      <div className="flex my-4 4xl:my-10 mx-2">
        <div className="flex gap-x-4 4xl:gap-x-8 ml-5 mt-4">
          <div className="relative inline-flex w-fit">
            <Menu>
              <div className="absolute bottom-auto left-auto right-0 top-0 z-10 inline-block -translate-y-[2px] translate-x-2/4 rotate-0 skew-x-0 skew-y-0 scale-x-100 scale-y-100 rounded-full bg-[#F65A27] px-[3.4px] 4xl:px-[8px] 4xl:py-[0.3px] py-[0.6px] border-2 border-white w-4 h-4 4xl:w-8 4xl:h-8">
                <p className="text-[8px] 4xl:text-[20px] text-white">3</p>
              </div>
              <MenuHandler>
                <div className=" flex items-center justify-center rounded-full bg-[#4D91FF] px-2 py-2 text-center text-white shadow-lg dark:text-gray-200 w-10 h-10 4xl:w-16 4xl:h-16">
                  <div className="relative 2xl:w-5 2xl:h-5 4xl:w-8 4xl:h-8">
                    <Image alt="" src="/message.svg" fill />
                  </div>
                </div>
              </MenuHandler>
              <MenuList>
                <MenuItem>Message 1</MenuItem>
                <MenuItem>Message 2</MenuItem>
                <MenuItem>Message 3</MenuItem>
              </MenuList>
            </Menu>
          </div>

          <div className="relative inline-flex w-fit">
            <Menu>
              <div className="absolute bottom-auto left-auto right-0 top-0 z-10 inline-block -translate-y-[2px] translate-x-2/4 rotate-0 skew-x-0 skew-y-0 scale-x-100 scale-y-100 rounded-full bg-[#F65A27] px-[3.4px] 4xl:px-[8px] 4xl:py-[0.3px] py-[0.6px] border-2 border-white w-4 h-4 4xl:w-8 4xl:h-8">
                <p className="text-[8px] 4xl:text-[20px] text-white">3</p>
              </div>
              <MenuHandler>
                <div className=" flex items-center justify-center rounded-full bg-[#4D91FF] px-2 py-2 text-center text-white shadow-lg dark:text-gray-200 w-10 h-10 4xl:w-16 4xl:h-16">
                  <div className="relative 2xl:w-5 2xl:h-5 4xl:w-10 4xl:h-10">
                    <Image alt="" src="/Alert.svg" fill />
                  </div>
                </div>
              </MenuHandler>
              <MenuList>
                <MenuItem>Message 1</MenuItem>
                <MenuItem>Message 2</MenuItem>
                <MenuItem>Message 3</MenuItem>
              </MenuList>
            </Menu>
          </div>
        </div>
        <div className="ml-8 mt-2 flex">
          <div className=" flex items-center justify-center rounded-full bg-[#FFBC35] px-2 py-2 text-center text-white shadow-lg dark:text-gray-200 w-16 h-16 4xl:w-24 4xl:h-24">
            <div className="relative 2xl:w-14 2xl:h-14 4xl:w-16 4xl:h-16">
              <Image alt="" src="/user.svg" fill />
            </div>
          </div>
          <div className="ml-3 mt-[-8px]  text-black">
            <p className="font-bold text-[20px] 4xl:text-[28px]">Demo User</p>
            <p className="text-[8px] 4xl:text-[14px]">
              Account Id: f48cda68-448b-4c67-9828-f48cda68
            </p>
            <p className="text-[8px] 4xl:text-[14px]">
              Namespace: Demo (c60c671bf1410535)
            </p>

            <p className="text-[8px] 4xl:text-[14px]">
              Usage Intent: Basic Analysis
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
}
